---
# tasks file for zabbix-agent-centos
# https://www.zabbix.com/documentation/2.4/manual/installation/install_from_packages
- name: Installing repository configuration package
  yum:
    name: http://repo.zabbix.com/zabbix/{{zabbix_full_version[:3]}}/rhel/{{ansible_distribution_major_version}}/x86_64/zabbix-agent-{{zabbix_full_version}}.el{{ansible_distribution_major_version}}.x86_64.rpm
    update_cache: yes
- name: Install zabbix agent
  yum:
    name: zabbix-agent
    update_cache: yes
